name: Deploy MultiK8s
on:
  push:
    branches:
      - master
 
env:
  SHA: $(git rev-parse HEAD)
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t vivekbhadauria/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true vivekbhadauria/react-test npm test
 
      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
 
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-364212
 
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
 
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-k8s-cluster
          location: asia-south1-a
 
      - name: Build
        run: |-
          docker build -t vivekbhadauria/multi-docker-fib-app-client:latest -t vivekbhadauria/multi-docker-fib-app-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t vivekbhadauria/multi-docker-fib-app-server:latest -t vivekbhadauria/multi-docker-fib-app-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t vivekbhadauria/multi-docker-fib-app-worker:latest -t vivekbhadauria/multi-docker-fib-app-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker
 
      - name: Push
        run: |-
          docker push vivekbhadauria/multi-docker-fib-app-client:latest
          docker push vivekbhadauria/multi-docker-fib-app-server:latest
          docker push vivekbhadauria/multi-docker-fib-app-worker:latest
 
          docker push vivekbhadauria/multi-docker-fib-app-client:${{ env.SHA }}
          docker push vivekbhadauria/multi-docker-fib-app-server:${{ env.SHA }}
          docker push vivekbhadauria/multi-docker-fib-app-worker:${{ env.SHA }}
 
      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=vivekbhadauria/multi-docker-fib-app-server:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=vivekbhadauria/multi-docker-fib-app-client:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=vivekbhadauria/multi-docker-fib-app-worker:${{ env.SHA }}